# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wacek Dziewulski's Dev Notes
email: wacekdziewulski@gmail.com
description:
  I've been a software developer for the last 10 years. Starting with C++,
  got to know Perl, created projects in Python, now making friends with Java.
  In my spare time, I'm an FPV drone pilot and run a blog and Youtube channel
  called 4Smigla.pl.
baseurl: "/blog"
url: "https://wacekdziewulski.ovh"
github_username:  wacekdziewulski

# Build settings
markdown: kramdown

theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
